; Auto-generated by tools/pack_items.py — do not edit
!zone item_gfx
ITEM_FRAME_COUNT = 25

item_frm_w
	!byte 14, 7, 4, 5, 10, 8, 5, 6, 8, 8, 8, 9, 4, 11, 14, 13, 13, 12, 8, 13, 4, 5, 8, 7, 6
item_frm_h
	!byte 8, 4, 15, 2, 13, 8, 2, 14, 3, 3, 2, 3, 3, 4, 5, 4, 7, 15, 2, 6, 5, 5, 4, 4, 8
item_frm_off_lo
	!byte 0, 56, 70, 102, 107, 177, 209, 214, 0, 16, 32, 40, 58, 66, 88, 130, 156, 208, 48, 56, 95, 107, 122, 138, 152
item_frm_off_hi
	!byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2
item_frm_ceil
	!byte 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

IF_TABLE_CHAIRS = 0
IF_CHANDELIER = 1
IF_HANGED_MAN = 2
IF_DOG_FOOD = 3
IF_TREE = 4
IF_URN = 5
IF_CEILING_LIGHT = 6
IF_SKELETON_CAGE = 7
IF_KEY_GOLD = 8
IF_KEY_SILVER = 9
IF_FOOD = 10
IF_FIRSTAID = 11
IF_AMMO_CLIP = 12
IF_MACHINEGUN = 13
IF_CHAINGUN = 14
IF_GIBS = 15
IF_WELL = 16
IF_FLAG = 17
IF_PUDDLE = 18
IF_BED = 19
IF_CROSS = 20
IF_CHALICE = 21
IF_BIBLE = 22
IF_CROWN = 23
IF_ONEUP = 24

; item_gfx_data label lives in wolf64.asm (ITM load → ITEM_SPRITES)

