; Auto-generated by tools/pack_items.py — do not edit
!zone item_gfx
ITEM_FRAME_COUNT = 19

item_frm_w
	!byte 14, 7, 6, 5, 10, 8, 5, 8, 7, 7, 8, 9, 4, 11, 15, 13, 13, 12, 13
item_frm_h
	!byte 8, 4, 16, 2, 13, 8, 2, 16, 3, 3, 2, 3, 3, 4, 5, 4, 7, 15, 6
item_frm_off_lo
	!byte 0, 56, 70, 118, 123, 193, 225, 230, 38, 52, 66, 74, 92, 100, 122, 167, 193, 245, 85
item_frm_off_hi
	!byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2
item_frm_ceil
	!byte 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

IF_TABLE_CHAIRS = 0
IF_CHANDELIER = 1
IF_HANGED_MAN = 2
IF_DOG_FOOD = 3
IF_TREE = 4
IF_URN = 5
IF_CEILING_LIGHT = 6
IF_SKELETON_CAGE = 7
IF_KEY_GOLD = 8
IF_KEY_SILVER = 9
IF_FOOD = 10
IF_FIRSTAID = 11
IF_AMMO_CLIP = 12
IF_MACHINEGUN = 13
IF_CHAINGUN = 14
IF_GIBS = 15
IF_WELL = 16
IF_FLAG = 17
IF_POTS = 18

; item_gfx_data label lives in wolf64.asm (ITM load → ITEM_SPRITES)

