; Auto-generated by tools/gen_weapon_sprites.py — do not edit
; Flush+centered sprite XY (knife: tip X at center, Y flush); runtime adds pose delta.
; Chaingun flash B uses distinct flash2 blobs + XY (slots 4..7).
!zone wpn_tables

KNIFE_SPR_PTR0 = (knife_spr0 - SCREEN) / 64
PISTOL_SPR_PTR0 = (pistol_spr0 - SCREEN) / 64
MACHINEGUN_SPR_PTR0 = (machinegun_spr0 - SCREEN) / 64
CHAINGUN_SPR_PTR0 = (chaingun_spr0 - SCREEN) / 64

wpn_nbody
	!byte 6, 6, 5, 4
wpn_nflash
	!byte 0, 2, 3, 4
wpn_en_body
	!byte 63, 63, 31, 15
wpn_en_fire
	!byte 63, 255, 255, 255
wpn_body_ptr0
	!byte KNIFE_SPR_PTR0, PISTOL_SPR_PTR0, MACHINEGUN_SPR_PTR0, CHAINGUN_SPR_PTR0
wpn_flash_ptr0
	!byte 0, (pistol_f1_white - SCREEN) / 64, (machinegun_f1_white - SCREEN) / 64, (chaingun_f1_white - SCREEN) / 64
wpn_flash_ptr1
	!byte 0, 0, 0, (chaingun_f2_white - SCREEN) / 64

; 8 slots per weapon (body 0..nbody-1)
wpn_spr_col
	!byte 1, 14, 10, 8, 11, 0, 0, 0, 1, 14, 10, 8, 11, 0, 0, 0, 1, 15, 14, 10, 11, 0, 0, 0, 1, 14, 3, 0, 0, 0, 0, 0
wpn_spr_x
	!byte 184, 188, 190, 188, 184, 188, 0, 0, 178, 162, 168, 168, 176, 160, 0, 0, 174, 174, 154, 170, 152, 0, 0, 0, 150, 170, 150, 162, 0, 0, 0, 0
wpn_spr_y
	!byte 204, 208, 220, 220, 204, 212, 0, 0, 206, 208, 224, 220, 202, 212, 0, 0, 220, 214, 214, 242, 216, 0, 0, 0, 208, 208, 208, 212, 0, 0, 0, 0

; 8 slots per weapon: flash1 (0..3) then flash2 (4..7)
wpn_flash_x
	!byte 0, 0, 0, 0, 0, 0, 0, 0, 176, 172, 0, 0, 0, 0, 0, 0, 166, 148, 176, 0, 0, 0, 0, 0, 160, 160, 136, 184, 160, 158, 138, 180
wpn_flash_y
	!byte 0, 0, 0, 0, 0, 0, 0, 0, 196, 192, 0, 0, 0, 0, 0, 0, 196, 190, 190, 0, 0, 0, 0, 0, 198, 186, 196, 196, 188, 176, 196, 196
