#!/usr/bin/env python3
"""Pack textures/menu key PNGs into 6 hi-res sprites (white + black pairs)."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "menu_hint_spr.asm"
PREVIEW = ROOT / "assets" / "menu_hint_preview.png"

SPR_W = 24
SPR_H = 21

GROUPS = (
	("ws", ROOT / "textures" / "menu" / "ws_sprite.png"),
	("ad", ROOT / "textures" / "menu" / "ad_sprite.png"),
	("return", ROOT / "textures" / "menu" / "return_sprite.png"),
)


def classify(im: Image.Image) -> tuple[list[list[int]], list[list[int]]]:
	rgba = im.convert("RGBA")
	w, h = rgba.size
	px = rgba.load()
	white = [[0] * w for _ in range(h)]
	black = [[0] * w for _ in range(h)]
	for y in range(h):
		for x in range(w):
			r, g, b, a = px[x, y]
			if a < 16:
				continue
			if r >= 240 and g >= 240 and b >= 240:
				white[y][x] = 1
			else:
				black[y][x] = 1
	return white, black


def pack_sprite(grid: list[list[int]], ox: int, oy: int) -> list[int]:
	raw = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = ox + col * 8 + bit
				y = oy + row
				if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def content_width(white: list[list[int]], black: list[list[int]]) -> int:
	w = 0
	for y, row in enumerate(white):
		for x, v in enumerate(row):
			if v or black[y][x]:
				if x + 1 > w:
					w = x + 1
	return w


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def main() -> None:
	blobs: list[int] = []
	widths: list[int] = []
	preview = Image.new("RGB", (SPR_W * 3 + 8, SPR_H), (40, 40, 40))
	pp = preview.load()

	for gi, (name, path) in enumerate(GROUPS):
		im = Image.open(path)
		white, black = classify(im)
		widths.append(content_width(white, black))
		blobs.extend(pack_sprite(white, 0, 0))
		blobs.extend(pack_sprite(black, 0, 0))
		ox = gi * (SPR_W + 4)
		gh = len(white)
		gw = len(white[0]) if gh else 0
		for y in range(min(SPR_H, gh)):
			for x in range(min(SPR_W, gw)):
				if white[y][x]:
					pp[ox + x, y] = (255, 255, 255)
				elif black[y][x]:
					pp[ox + x, y] = (0, 0, 0)

	lines = [
		"; Auto-generated by tools/gen_menu_hint_sprites.py",
		"HINT_SPR_COUNT\t= 6",
		f"HINT_SPR_W\t= {SPR_W}",
		f"HINT_GROUP_W0\t= {widths[0]}\t; ws opaque width",
		f"HINT_GROUP_W1\t= {widths[1]}\t; ad opaque width",
		f"HINT_GROUP_W2\t= {widths[2]}\t; return opaque width",
		"",
		"menu_hint_spr",
	]
	lines.extend(fmt_bytes(blobs))
	lines.append("")

	OUT.write_text("\n".join(lines), encoding="utf-8")
	PREVIEW.parent.mkdir(exist_ok=True)
	preview.save(PREVIEW)
	print(
		f"wrote {OUT.relative_to(ROOT)} widths={widths} "
		f"+ {PREVIEW.relative_to(ROOT)}"
	)


if __name__ == "__main__":
	main()
