#!/usr/bin/env python3
"""Build menufont from assets/menufont.png → asm + ECM charset + ecm_map."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "assets" / "menufont.png"
ASM_OUT = ROOT / "generated" / "assets" / "menufont.asm"
CHARSET_OUT = ROOT / "generated" / "src" / "menufont_charset.asm"
MAP_OUT = ROOT / "generated" / "src" / "ecm_map.asm"
INC_OUT = ROOT / "generated" / "src" / "menufont_ecm.inc"

# Option-menu ECM set (≤64). Text screens use hires bitmap + full font.
ECM_CHARS = " !'(),-./0123456789:?@ABCDEFGHIMNOPQRSTVWabcdefghijklmnoprstuvwy"


def fmt(g: list[int]) -> str:
	return ",".join(f"${b:02x}" for b in g)


def glyph_from_png(px, col: int, row: int) -> list[int]:
	out = []
	for y in range(8):
		b = 0
		for x in range(8):
			if px[col * 8 + x, row * 8 + y] > 0:
				b |= 0x80 >> x
		out.append(b)
	return out


def main() -> None:
	im = Image.open(PNG)
	if im.size != (64, 96):
		raise SystemExit(f"menufont.png expected 64x96, got {im.size}")
	px = im.load()

	for out_path in (ASM_OUT, CHARSET_OUT, MAP_OUT, INC_OUT):
		out_path.parent.mkdir(parents=True, exist_ok=True)

	ascii_glyphs = {
		32 + i: glyph_from_png(px, i % 8, i // 8) for i in range(96)
	}

	lines = [
		"; Auto-generated from assets/menufont.png by tools/gen_menufont.py",
		"!zone menufont",
		"menufont_udgs",
	]
	for ch in range(32, 128):
		g = ascii_glyphs[ch]
		note = "space" if ch == 32 else repr(chr(ch))
		lines.append(f"\t!byte {fmt(g)}\t; {ch} {note}")
	ASM_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

	seen: list[str] = []
	for c in ECM_CHARS:
		if c not in seen:
			seen.append(c)
	if len(seen) > 64:
		raise SystemExit(f"ECM set has {len(seen)} chars (max 64)")

	ecm_index: dict[int, int] = {}
	glyphs: list[list[int]] = []
	for i, c in enumerate(seen):
		code = ord(c)
		glyphs.append(ascii_glyphs[code])
		ecm_index[code] = i
		if "a" <= c <= "z":
			ecm_index[ord(c) - ord("a") + 1] = i	# screencode
		if "A" <= c <= "Z":
			ecm_index[code] = i

	cursor_i = ecm_index[ord("@")]

	out = [
		"; ECM charset @ $3800 — tools/gen_menufont.py",
		"!zone menufont_charset",
		"menufont_charset",
	]
	for i, g in enumerate(glyphs):
		out.append(f"\t!byte {fmt(g)}\t; {i} {seen[i]!r}")
	while len(glyphs) < 64:
		out.append(f"\t!byte {fmt([0] * 8)}\t; pad")
		glyphs.append([0] * 8)
	CHARSET_OUT.write_text("\n".join(out) + "\n", encoding="utf-8")

	INC_OUT.write_text(
		f"; Generated by tools/gen_menufont.py\nMENU_CURSOR = {cursor_i}\n",
		encoding="utf-8",
	)

	map_lines = [
		"; ASCII/screen-code → ECM index; $ff = missing — tools/gen_menufont.py",
		"ecm_map",
	]
	for i in range(128):
		map_lines.append(f"\t!byte ${ecm_index.get(i, 0xFF):02x}")
	MAP_OUT.write_text("\n".join(map_lines) + "\n", encoding="utf-8")

	print(f"ECM glyphs={len(seen)} cursor={cursor_i} -> {CHARSET_OUT.name}, {MAP_OUT.name}, {INC_OUT.name}")


if __name__ == "__main__":
	main()
