# Generate src/bss.asm — boot-overlay BSS (LOADER_BASE .. REBOOT_STUB).
# col_wallz_h / col_enemy live after end_sfx (see wolf64.asm).
# Doors / profiler / enemy temps / SoA stay as normal !fill in wolf64.asm.
from pathlib import Path

REBOOT_STUB = 0x08C0

low = [
	("col_texid", 40),
	("col_half_h", 40),
	("col_texx", 40),
	("col_wallz_l", 40),
	("load_namelen", 1),
	("load_name_l", 1),
	("load_name_h", 1),
	("load_do_pad", 1),
	("load_jiffy0", 1),
	("episode", 1),
	("level_num", 1),
	("secret_from", 1),
	("load_in_play", 1),
]

lines = [
	"; BSS overlays disposable boot at LOADER_BASE..REBOOT_STUB-1 (not emitted).",
	"; col_wallz_h / col_enemy after end_sfx; reboot stub @ REBOOT_STUB; difficulty @ $08FF.",
	"; Generated by tools/gen_bss.py — chained '=' for ACME multi-pass.",
	"!zone bss",
	"",
]
prev = "LOADER_BASE"
prev_size = 0
for i, (name, size) in enumerate(low):
	if i == 0:
		lines.append(f"{name}\t= {prev}")
	else:
		lines.append(f"{name}\t= {prev} + {prev_size}")
	prev = name
	prev_size = size
lines.append(f"end_bss\t= {prev} + {prev_size}")
lines += [
	"!if end_bss > REBOOT_STUB {",
	'\t!error "BSS overlaps REBOOT_STUB; end_bss=$", end_bss',
	"}",
	"",
]
out_path = Path(__file__).resolve().parent.parent / "generated" / "src" / "bss.asm"
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines), encoding="utf-8")
end = 0x801 + sum(s for _, s in low)
print(f"end_bss=${end:04X} (limit REBOOT_STUB=${REBOOT_STUB:04X}) fit={end <= REBOOT_STUB}")
