#!/usr/bin/env python3
"""Build src/menu_text.asm from control/credits/readthis txt files."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "generated" / "src" / "menu_text.asm"

# label, source txt (no yellow title — body only)
SCREENS = (
	("control_text", ROOT / "control.txt"),
	("credits_text", ROOT / "credits.txt"),
	("order_text", ROOT / "order.txt"),
	("readthis1_text", ROOT / "readthis1.txt"),
	("readthis2a_text", ROOT / "readthis2a.txt"),
	("readthis2b_text", ROOT / "readthis2b.txt"),
	("readthis3_text", ROOT / "readthis3.txt"),
	("ending1_text", ROOT / "ending1.txt"),
	("ending2_text", ROOT / "ending2.txt"),
)


def scr_pieces(s: str) -> str:
	"""This ACME build/version doesn't accept \\" (or "" doubling) inside a
	!scr string — both were tried and rejected with "Garbage data at end of
	statement". Split on '"' instead and splice in the raw screen-code byte
	(34, same as ASCII since '"' falls in the space..? unshifted range)."""
	parts = s.split('"')
	pieces: list[str] = []
	for i, part in enumerate(parts):
		if part:
			pieces.append(f'"{part}"')
		if i < len(parts) - 1:
			pieces.append("34")
	if not pieces:
		pieces = ['""']
	return ",".join(pieces)


PAGE_BREAK = "^"


def page_label(base: str, index: int) -> str:
	"""credits_text + page 2 -> credits2_text"""
	if index == 0:
		return base
	stem, _, suffix = base.partition("_text")
	return f"{stem}{index + 1}_text"


def split_pages(lines: list[str]) -> list[list[str]]:
	pages: list[list[str]] = [[]]
	for line in lines:
		if line.strip() == PAGE_BREAK:
			if pages[-1]:
				pages.append([])
			continue
		pages[-1].append(line)
	while pages and not pages[-1]:
		pages.pop()
	return pages if pages else [[]]


def emit_page(label: str, lines: list[str]) -> list[str]:
	out = [f"{label}"]
	for line in lines:
		body = line if line.strip() else " "
		out.append(f"\t!scr {scr_pieces(body)},0")
	out.append("\t!byte 0")
	out.append("")
	return out


def emit_blob(label: str, path: Path) -> list[str]:
	lines = path.read_text(encoding="utf-8").splitlines()
	while lines and not lines[-1].strip():
		lines.pop()
	pages = split_pages(lines)
	if len(pages) <= 1:
		return emit_page(label, pages[0] if pages else [])
	out: list[str] = []
	for i, page in enumerate(pages):
		out.extend(emit_page(page_label(label, i), page))
	return out


def main() -> None:
	out: list[str] = [
		"; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root",
		"",
	]
	for label, path in SCREENS:
		if not path.is_file():
			raise SystemExit(f"missing {path}")
		out.extend(emit_blob(label, path))
	OUT.parent.mkdir(parents=True, exist_ok=True)
	OUT.write_text("\n".join(out), encoding="utf-8")
	print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
	main()
