#!/usr/bin/env python3
"""Generate enemy vertical scale step table: (src_h<<8)/dst_h for dst 1..48."""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "generated" / "src" / "enemy_painters.asm"
SRC_H = 16
MAX_H = 48


def main() -> int:
    steps = []
    for h in range(MAX_H + 1):
        if h < 1:
            steps.append(0)
        else:
            steps.append(min(0xFFFF, (SRC_H << 8) // h))
    lines = [
        "; Auto-generated by tools/gen_enemy_painters.py — do not edit",
        "!zone enemy_painters",
        f"ENEMY_MAX_H = {MAX_H}",
        f"ENEMY_SRC_H = {SRC_H}",
        "",
        "; 8.8 step: src_row += step each chunky screen row (src height 16)",
        "enemy_vstep_lo",
        "\t!byte " + ", ".join(str(s & 0xFF) for s in steps),
        "enemy_vstep_hi",
        "\t!byte " + ", ".join(str((s >> 8) & 0xFF) for s in steps),
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({MAX_H + 1} steps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
