#!/usr/bin/env python3
"""Pack textures/menu/pistolcursor.png into 4 hi-res colour-layer sprites."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "textures" / "menu" / "pistolcursor.png"
OUT = ROOT / "generated" / "src" / "menu_cursor_spr.asm"
PREVIEW = ROOT / "generated" / "assets" / "menu_cursor_preview.png"

SPR_W = 24
SPR_H = 21

# Brighter first (VIC priority: lower sprite # in front).
C64_COLS = (
	(1, "white"),
	(15, "ltgrey"),
	(12, "grey"),
	(11, "dkgrey"),
)


def pack_sprite(grid: list[list[int]], ox: int, oy: int) -> list[int]:
	raw = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = ox + col * 8 + bit
				y = oy + row
				if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def main() -> None:
	im = Image.open(PNG).convert("RGBA")
	w, h = im.size
	px = im.load()

	# Collect opaque colours by luminance (brightest first).
	by_lum: dict[tuple[int, int, int], int] = {}
	for y in range(h):
		for x in range(w):
			r, g, b, a = px[x, y]
			if a < 16:
				continue
			if r + g + b < 24:
				continue
			by_lum[(r, g, b)] = r + g + b
	ordered = sorted(by_lum.keys(), key=lambda c: -by_lum[c])
	if len(ordered) != 4:
		raise SystemExit(f"expected 4 opaque greys, got {len(ordered)}: {ordered}")

	layers: list[list[list[int]]] = []
	for rgb in ordered:
		grid = [[0] * w for _ in range(h)]
		for y in range(h):
			for x in range(w):
				r, g, b, a = px[x, y]
				if a >= 16 and (r, g, b) == rgb:
					grid[y][x] = 1
		layers.append(grid)

	blobs: list[int] = []
	for grid in layers:
		blobs.extend(pack_sprite(grid, 0, 0))

	preview = Image.new("RGB", (SPR_W, SPR_H), (40, 40, 40))
	pp = preview.load()
	# Draw darkest first so white ends on top.
	preview_rgb = [
		(68, 68, 68),
		(120, 120, 120),
		(180, 180, 180),
		(255, 255, 255),
	]
	for li in reversed(range(4)):
		grid = layers[li]
		for y in range(min(SPR_H, h)):
			for x in range(min(SPR_W, w)):
				if grid[y][x]:
					pp[x, y] = preview_rgb[li]

	col_bytes = ",".join(f"${c:02x}" for c, _ in C64_COLS)
	lines = [
		"; Auto-generated by tools/gen_menu_cursor_sprites.py",
		"CURSOR_SPR_COUNT\t= 4",
		f"CURSOR_SPR_W\t= {SPR_W}",
		f"cursor_spr_cols\t!byte {col_bytes}\t; white, ltgrey, grey, dkgrey",
		"",
		"menu_cursor_spr",
	]
	lines.extend(fmt_bytes(blobs))
	lines.append("")

	OUT.parent.mkdir(parents=True, exist_ok=True)
	OUT.write_text("\n".join(lines), encoding="utf-8")
	PREVIEW.parent.mkdir(parents=True, exist_ok=True)
	preview.save(PREVIEW)
	print(
		f"wrote {OUT.relative_to(ROOT)} colours={[by_lum[c] for c in ordered]} "
		f"+ {PREVIEW.relative_to(ROOT)}"
	)


if __name__ == "__main__":
	main()
