#!/usr/bin/env python3
"""Build src/menu_text.asm from control/credits/readthis txt files."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "menu_text.asm"

# label, source txt (no yellow title — body only)
SCREENS = (
	("control_text", ROOT / "control.txt"),
	("credits_text", ROOT / "credits.txt"),
	("order_text", ROOT / "order.txt"),
	("readthis1_text", ROOT / "readthis1.txt"),
	("readthis2a_text", ROOT / "readthis2a.txt"),
	("readthis2b_text", ROOT / "readthis2b.txt"),
	("readthis3_text", ROOT / "readthis3.txt"),
	("ending1_text", ROOT / "ending1.txt"),
	("ending2_text", ROOT / "ending2.txt"),
)


def esc_scr(s: str) -> str:
	"""Escape for ACME !scr \"...\"."""
	return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_blob(label: str, path: Path) -> list[str]:
	lines = path.read_text(encoding="utf-8").splitlines()
	while lines and not lines[-1].strip():
		lines.pop()
	out = [f"{label}"]
	for line in lines:
		body = line if line.strip() else " "
		out.append(f'\t!scr "{esc_scr(body)}",0')
	out.append("\t!byte 0")
	out.append("")
	return out


def main() -> None:
	out: list[str] = [
		"; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root",
		"",
	]
	for label, path in SCREENS:
		if not path.is_file():
			raise SystemExit(f"missing {path}")
		out.extend(emit_blob(label, path))
	OUT.write_text("\n".join(out), encoding="utf-8")
	print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
	main()
