#!/usr/bin/env python3
"""Emit src/boot_syms.asm from wolf64.lbl for boot.asm (separate ACME pass)."""
from __future__ import annotations

import re
import sys
from pathlib import Path

LBL_RE = re.compile(r"^al C:([0-9a-fA-F]+)\s+\.(\S+)\s*$")
NEED = ("enemy_install", "locode_entry")


def main() -> None:
	root = Path(__file__).resolve().parents[1]
	lbl_path = root / "generated" / "wolf64.lbl"
	out_path = root / "generated" / "src" / "boot_syms.asm"
	out_path.parent.mkdir(parents=True, exist_ok=True)
	syms: dict[str, int] = {}
	for line in lbl_path.read_text(encoding="utf-8", errors="replace").splitlines():
		m = LBL_RE.match(line.strip())
		if m:
			syms[m.group(2)] = int(m.group(1), 16)
	missing = [n for n in NEED if n not in syms]
	if missing:
		print(f"gen_boot_syms: missing {missing} in {lbl_path}", file=sys.stderr)
		sys.exit(1)
	lines = [
		"; Generated by tools/gen_boot_syms.py — do not edit",
		f"enemy_install\t= ${syms['enemy_install']:04X}",
		f"locode_entry\t= ${syms['locode_entry']:04X}",
		"",
	]
	out_path.write_text("\n".join(lines), encoding="utf-8")
	print(f"Wrote {out_path} (install=${syms['enemy_install']:04X} entry=${syms['locode_entry']:04X})")


if __name__ == "__main__":
	main()
