#!/usr/bin/env python3
"""Pack textures/bjhead into 10 VIC hi-res sprites (24×21 windows)."""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_walls import C64_PALETTE, nearest_c64  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "textures" / "bjhead"
OUT = ROOT / "generated" / "src" / "bjhead_spr.asm"
PREVIEW = ROOT / "generated" / "assets" / "bjhead_spr_preview.png"

SPR_W = 24
SPR_H = 21
PNG_W = 24
PNG_H = 28

# HUD origin (148, 0) → VIC X=172, Y=50. Sprite at HUD y covers PNG y .. y+20.
BJH_X = 172
BJH_Y_BASE = 50
BJH_Y_WHITE = 54
BJH_Y_LOOK = 57
BJH_Y_BLOOD = 57
BJH_Y_DEADLT = 53
BJH_Y_DEADRED = 57

# (file, c64 colour, hud_y) — memory order = sprite slots 0..9, ptrs $20..$29
# HUD y = PNG row0 (origin at 0); sprite is 21 tall (png_y0 .. png_y0+20).
SLOTS = (
    ("base_details.png", 2, 0),
    ("base_details.png", 10, 0),
    ("base_details.png", 1, 4),
    ("blood_1.png", 10, 7),
    ("blood_2.png", 10, 7),
    ("look_forward.png", 2, 7),
    ("look_left.png", 2, 7),
    ("look_right.png", 2, 7),
    ("dead_details.png", 2, 7),
    ("dead_details.png", 10, 3),
)


def pack_sprite(grid: list[list[int]]) -> list[int]:
    raw = []
    gh = len(grid)
    gw = len(grid[0]) if gh else 0
    for row in range(SPR_H):
        for col in range(3):
            b = 0
            for bit in range(8):
                x = col * 8 + bit
                y = row
                if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
                    b |= 0x80 >> bit
            raw.append(b)
    raw.append(0)
    return raw


def layer_window(path: Path, colour: int, png_y0: int) -> list[list[int]]:
    im = Image.open(path).convert("RGBA")
    if im.size != (PNG_W, PNG_H):
        raise SystemExit(f"{path.name}: expected {PNG_W}×{PNG_H}, got {im.size}")
    px = im.load()
    grid = [[0] * SPR_W for _ in range(SPR_H)]
    for row in range(SPR_H):
        py = png_y0 + row
        for x in range(SPR_W):
            if not (0 <= py < PNG_H):
                continue
            r, g, b, a = px[x, py]
            if a < 16:
                continue
            if nearest_c64((r, g, b)) == colour:
                grid[row][x] = 1
    return grid


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
    return lines


def main() -> None:
    blobs: list[int] = []
    layers: list[tuple[int, list[list[int]]]] = []
    for name, colour, hud_y in SLOTS:
        png_y0 = hud_y
        grid = layer_window(SRC / name, colour, png_y0)
        nset = sum(sum(row) for row in grid)
        print(f"  slot {len(layers)} {name} c64=${colour:x} hud_y={hud_y} png {png_y0}..{png_y0 + 20} set={nset}")
        if nset == 0:
            raise SystemExit(f"{name} colour ${colour:x} packed empty")
        blobs.extend(pack_sprite(grid))
        layers.append((colour, grid))

    if len(blobs) != 10 * 64:
        raise SystemExit(f"expected 640 bytes, got {len(blobs)}")

    # Composite preview: yellow silhouette + layers back-to-front at HUD offsets.
    preview = Image.new("RGB", (PNG_W, PNG_H), (0, 0, 0))
    pp = preview.load()
    yel = SRC / "base_yellow.png"
    if yel.is_file():
        yim = Image.open(yel).convert("RGBA")
        ypx = yim.load()
        for y in range(PNG_H):
            for x in range(PNG_W):
                r, g, b, a = ypx[x, y]
                if a >= 16 and nearest_c64((r, g, b)) == 7:
                    pp[x, y] = C64_PALETTE[7]
    # Draw red, ltred, white, blood, look (later slots on top among same pixels).
    draw_order = (0, 1, 2, 3, 5)  # base red/ltred/white, blood1, look_forward
    for si in draw_order:
        colour, grid = layers[si]
        _, _, hud_y = SLOTS[si]
        png_y0 = hud_y
        rgb = C64_PALETTE[colour]
        for row in range(SPR_H):
            py = png_y0 + row
            if not (0 <= py < PNG_H):
                continue
            for x in range(SPR_W):
                if grid[row][x]:
                    pp[x, py] = rgb

    lines = [
        "; Auto-generated by tools/gen_bjhead_sprites.py — 10×64 hi-res @ $4800",
        "BJH_COUNT\t= 10",
        f"BJH_PTR_RED\t= $20",
        f"BJH_PTR_LTRED\t= $21",
        f"BJH_PTR_WHITE\t= $22",
        f"BJH_PTR_BLOOD1\t= $23",
        f"BJH_PTR_BLOOD2\t= $24",
        f"BJH_PTR_LOOKF\t= $25",
        f"BJH_PTR_LOOKL\t= $26",
        f"BJH_PTR_LOOKR\t= $27",
        f"BJH_PTR_DEADRED\t= $28",
        f"BJH_PTR_DEADLT\t= $29",
        f"BJH_X\t\t= {BJH_X}",
        f"BJH_Y_BASE\t= {BJH_Y_BASE}",
        f"BJH_Y_WHITE\t= {BJH_Y_WHITE}",
        f"BJH_Y_LOOK\t= {BJH_Y_LOOK}",
        f"BJH_Y_BLOOD\t= {BJH_Y_BLOOD}",
        f"BJH_Y_DEADLT\t= {BJH_Y_DEADLT}",
        f"BJH_Y_DEADRED\t= {BJH_Y_DEADRED}",
        "BJH_EN_ALIVE\t= $1d\t; look + white + ltred + red",
        "BJH_EN_BLOOD\t= $1f\t; + blood",
        "BJH_EN_DEAD\t= $18\t; ltred + red (dead_details)",
        "",
        "bjh_spr",
    ]
    lines.extend(fmt_bytes(blobs))
    lines.extend(
        [
            "",
            "; Wolf look index: 0=left, 1=center, 2=right (3 remapped to 1)",
            "bjh_look_ptr\t!byte BJH_PTR_LOOKL, BJH_PTR_LOOKF, BJH_PTR_LOOKR",
            "bjh_blood_ptr\t!byte 0, BJH_PTR_BLOOD1, BJH_PTR_BLOOD2",
            "bjh_blood_col\t!byte 0, $0a, $02\t; none, ltred, red",
            "",
        ]
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    preview.save(PREVIEW)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(blobs)} B) + {PREVIEW.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
