# Generate src/bss.asm — only boot-overlay BSS (LOADER_BASE .. LOCODE_BASE).
# Doors / profiler / enemy temps / SoA stay as normal !fill in wolf64.asm.
from pathlib import Path

low = [
	("col_texid", 40),
	("col_half_h", 40),
	("col_texx", 40),
	("col_wallz_l", 40),
	("col_wallz_h", 40),
	("col_enemy", 40),
	("sound_priority", 1),
	("sound_count", 1),
	("sound_max", 1),
	("ps_save_x", 1),
	("ps_save_y", 1),
	("load_namelen", 1),
	("load_name_l", 1),
	("load_name_h", 1),
	("load_do_pad", 1),
	("load_jiffy0", 1),
	("episode", 1),
	("level_num", 1),
]

lines = [
	"; BSS overlays disposable boot at LOADER_BASE..LOCODE_BASE-1 (not emitted).",
	"; Other BSS (!fill) lives after locode / after painters as before.",
	"; Generated by tools/gen_bss.py — chained '=' for ACME multi-pass.",
	"!zone bss",
	"",
]
prev = "LOADER_BASE"
prev_size = 0
for i, (name, size) in enumerate(low):
	if i == 0:
		lines.append(f"{name}\t= {prev}")
	else:
		lines.append(f"{name}\t= {prev} + {prev_size}")
	prev = name
	prev_size = size
lines.append(f"end_bss\t= {prev} + {prev_size}")
lines += [
	"!if end_bss > LOCODE_BASE {",
	'\t!error "BSS overlaps LOCODE_BASE; end_bss=$", end_bss',
	"}",
	"",
]
Path(__file__).resolve().parent.parent.joinpath("src", "bss.asm").write_text(
	"\n".join(lines), encoding="utf-8"
)
end = 0x801 + sum(s for _, s in low)
print(f"end_bss=${end:04X} (limit LOCODE_BASE) fit={end <= 0x900}")
