#!/usr/bin/env python3
"""
Generate 50 compiled wall-height column painters (TechDesignDoc §4).

Writes src/painters.asm only. Jump/SMC tables come from make_painter_tables.py
after painters.bin is assembled.

Entry: X = texx*8, Y = column. Stores go to (view_rowN),y — back screen matrix.

Viewport letterbox: only cells 2..21 (20 cells = 40 chunky rows). Cells 0..1 and
22..23 are a static border (see fill_view_border). Columns 0 and 39 are skipped
in the cast/paint loops (38 columns).
"""

from __future__ import annotations

from pathlib import Path

SKY = 0xBB
FLOOR = 0xCC
NUM_CELLS = 24
CELL_LO = 2				# inclusive
CELL_HI = 22				# exclusive → cells 2..21
HALF_VIEW = 48
OUT = Path(__file__).resolve().parents[1] / "src" / "painters.asm"


def tex_row(v: int, h: int) -> int:
    v0 = 24 - h
    t = ((v - v0) * 8) // h
    if t < 0:
        return 0
    if t > 15:
        return 15
    return t


def kind(v: int, h: int) -> str:
    v0 = 24 - h
    v1 = 24 + h
    if v < max(0, v0):
        return "sky"
    if v >= min(HALF_VIEW, v1):
        return "floor"
    return "wall"


def emit_run(lines: list[str], value: int, start: int, count: int) -> None:
    if count <= 0:
        return
    lines.append(f"\tlda #${value:02x}")
    for i in range(count):
        lines.append(f"\tsta (view_row{start + i}),y")


def main() -> None:
    code: list[str] = [
        "; AUTO-GENERATED by tools/gen_painters.py — do not edit",
        "; Compiled height painters (half_h 1..50) → back screen matrix",
        "; Entry: X = texx*8, Y = column; cells 2..21 only (38x40 chunky view)",
        "!zone painters",
        "",
    ]

    for h in range(1, 51):
        label = f"painter_h{h:02d}"
        code.append(f"; ---- half_h = {h} ----")
        code.append(label)

        run_val: int | None = None
        run_n = 0
        run_start = 0
        cell_i = 0

        def flush_run() -> None:
            nonlocal run_val, run_n, run_start
            if run_val is not None and run_n:
                emit_run(code, run_val, run_start, run_n)
            run_val = None
            run_n = 0

        def tex_lda(byte_off: int) -> None:
            nonlocal cell_i
            pl = f"smc_h{h:02d}_{cell_i}"
            cell_i += 1
            code.append(f"{pl}")
            code.append(f"\tlda TEXTURES + {byte_off},x")

        for c in range(CELL_LO, CELL_HI):
            vt, vb = 2 * c, 2 * c + 1
            kt, kb = kind(vt, h), kind(vb, h)

            if kt == "sky" and kb == "sky":
                if run_val == SKY:
                    run_n += 1
                else:
                    flush_run()
                    run_val, run_n, run_start = SKY, 1, c
                continue
            if kt == "floor" and kb == "floor":
                if run_val == FLOOR:
                    run_n += 1
                else:
                    flush_run()
                    run_val, run_n, run_start = FLOOR, 1, c
                continue

            flush_run()

            if kt == "wall" and kb == "wall":
                tr_t, tr_b = tex_row(vt, h), tex_row(vb, h)
                if (
                    tr_t == (tr_b ^ 1)
                    and (tr_t >> 1) == (tr_b >> 1)
                    and (tr_t & 1) == 0
                ):
                    tex_lda(tr_t >> 1)
                    code.append(f"\tsta (view_row{c}),y")
                    continue

            if kt == "sky":
                code.append("\tlda #$b0")
                code.append("\tsta tmp0")
            elif kt == "floor":
                code.append("\tlda #$c0")
                code.append("\tsta tmp0")
            else:
                tr = tex_row(vt, h)
                tex_lda(tr >> 1)
                if tr & 1:
                    code.append("\tand #$0f")
                    code.append("\tasl")
                    code.append("\tasl")
                    code.append("\tasl")
                    code.append("\tasl")
                else:
                    code.append("\tand #$f0")
                code.append("\tsta tmp0")

            if kb == "sky":
                code.append("\tlda tmp0")
                code.append("\tora #$0b")
            elif kb == "floor":
                code.append("\tlda tmp0")
                code.append("\tora #$0c")
            else:
                tr = tex_row(vb, h)
                tex_lda(tr >> 1)
                if tr & 1:
                    code.append("\tand #$0f")
                else:
                    code.append("\tlsr")
                    code.append("\tlsr")
                    code.append("\tlsr")
                    code.append("\tlsr")
                code.append("\tora tmp0")

            code.append(f"\tsta (view_row{c}),y")

        flush_run()
        code.append("\trts")
        code.append("")

    code.append("painters_end")
    code.append("")
    OUT.write_text("\n".join(code) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
