#!/usr/bin/env python3
"""Build src/menu_logo.asm from textures/h_wolflogo_twocolour.png.

White pixels → hires bitmap ink; non-black non-white (red/pink) → sprite ink.
Badge is 2 columns wider than the logo on each side.
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PNG = ROOT / "textures" / "h_wolflogo_twocolour.png"
OUT = ROOT / "generated" / "src" / "menu_logo.asm"
PREVIEW = ROOT / "generated" / "assets" / "menu_logo_preview.png"

LOGO_W = 160
LOGO_H = 28
BADGE_PAD_COLS = 2			# each side
BADGE_COLS = LOGO_W // 8 + BADGE_PAD_COLS * 2	# 24
BADGE_ROWS = 5
SPR_COUNT = 7
SPR_W = 24
SPR_H = 21


def classify(im: Image.Image) -> tuple[list[list[int]], list[list[int]]]:
	"""Return (white_grid, red_grid) 0/1 masks, logo size."""
	rgb = im.convert("RGB")
	w, h = rgb.size
	px = rgb.load()
	white = [[0] * w for _ in range(h)]
	red = [[0] * w for _ in range(h)]
	for y in range(h):
		for x in range(w):
			r, g, b = px[x, y]
			if r + g + b < 24:
				continue
			# Near-white → bitmap; anything else lit → sprite red
			if r >= 240 and g >= 240 and b >= 240:
				white[y][x] = 1
			else:
				red[y][x] = 1
	return white, red


def pack_hires_cell(grid: list[list[int]], cx: int, cy: int) -> list[int]:
	out = []
	for row in range(8):
		b = 0
		py = cy * 8 + row
		for bit in range(8):
			px = cx * 8 + bit
			if 0 <= py < len(grid) and 0 <= px < len(grid[0]) and grid[py][px]:
				b |= 0x80 >> bit
		out.append(b)
	return out


def pack_sprite(grid: list[list[int]], ox: int, oy: int) -> list[int]:
	raw = []
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = ox + col * 8 + bit
				y = oy + row
				if 0 <= y < len(grid) and 0 <= x < len(grid[0]) and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def pad_into_badge(src: list[list[int]], pad_x: int, pad_y: int, bw: int, bh: int) -> list[list[int]]:
	grid = [[0] * bw for _ in range(bh)]
	for y, row in enumerate(src):
		for x, v in enumerate(row):
			if v:
				grid[pad_y + y][pad_x + x] = 1
	return grid


def main() -> None:
	im = Image.open(PNG)
	if im.size != (LOGO_W, LOGO_H):
		im = im.resize((LOGO_W, LOGO_H), Image.Resampling.NEAREST)
	white, red = classify(im)

	badge_h = BADGE_ROWS * 8
	badge_w = BADGE_COLS * 8
	pad_y = (badge_h - LOGO_H) // 2
	pad_x = BADGE_PAD_COLS * 8

	white_g = pad_into_badge(white, pad_x, pad_y, badge_w, badge_h)
	red_g = pad_into_badge(red, pad_x, pad_y, badge_w, badge_h)

	# Sprite Y: cover red's vertical span (fits in 21px)
	red_rows = [y for y in range(LOGO_H) if any(red[y])]
	spr_off_y = min(red_rows) if red_rows else 0
	if red_rows and max(red_rows) - spr_off_y + 1 > SPR_H:
		spr_off_y = max(0, max(red_rows) - SPR_H + 1)
	spr_oy = pad_y + spr_off_y

	cells: list[int] = []
	for cy in range(BADGE_ROWS):
		for cx in range(BADGE_COLS):
			cells.extend(pack_hires_cell(white_g, cx, cy))

	sprites: list[int] = []
	for i in range(SPR_COUNT):
		ox = pad_x + i * SPR_W
		sprites.extend(pack_sprite(red_g, ox, spr_oy))

	prev = Image.new("RGB", (badge_w, badge_h), (0, 0, 0))
	pp = prev.load()
	for y in range(badge_h):
		for x in range(badge_w):
			if red_g[y][x]:
				pp[x, y] = (136, 0, 0)
			elif white_g[y][x]:
				pp[x, y] = (255, 255, 255)
	PREVIEW.parent.mkdir(parents=True, exist_ok=True)
	prev.save(PREVIEW)

	lines = [
		"; Auto-generated by tools/gen_menu_logo.py from h_wolflogo_twocolour.png",
		f"MENU_LOGO_COLS\t= {BADGE_COLS}",
		f"MENU_LOGO_ROWS\t= {BADGE_ROWS}",
		f"MENU_LOGO_SPR_COUNT\t= {SPR_COUNT}",
		f"MENU_LOGO_PAD_Y\t= {pad_y}\t; px from badge top to logo",
		f"MENU_LOGO_SPR_OFF_Y\t= {spr_off_y}\t; px from logo top to sprite top",
		"",
		"menu_logo_data",
	]
	lines.extend(fmt_bytes(cells))
	lines.append("")
	lines.append("menu_logo_spr")
	lines.extend(fmt_bytes(sprites))
	lines.append("")

	OUT.parent.mkdir(parents=True, exist_ok=True)
	OUT.write_text("\n".join(lines), encoding="utf-8")
	print(
		f"wrote {OUT.relative_to(ROOT)} cols={BADGE_COLS} "
		f"spr_off_y={spr_off_y} + {PREVIEW.relative_to(ROOT)}"
	)


if __name__ == "__main__":
	main()
