#!/usr/bin/env python3
"""
Strip CORE PC-speaker chunks from shareware AUDIOT.WL1 / AUDIOHED.WL1.
Decimate 3x (keep every 3rd sample) for ~50 Hz playback.
Emits src/pcsounds.asm + src/pcsfreq.asm (SID Fn hi LUT, NTSC φ2; lo fixed $80).
"""
from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SHAREWARE = ROOT / "shareware"
OUT_SOUNDS = ROOT / "src" / "pcsounds.asm"
OUT_FREQ = ROOT / "src" / "pcsfreq.asm"

# Wolf soundnames index → local CORE slot (order = sound_table)
CORE = [
    (0, "HITWALL"),
    (9, "PLAYERDEATH"),
    (10, "DOGDEATH"),
    (11, "ATKGATLING"),
    (16, "TAKEDAMAGE"),
    (18, "OPENDOOR"),
    (19, "CLOSEDOOR"),
    (21, "HALT"),
    (22, "DEATHSCREAM2"),
    (24, "ATKPISTOL"),
    (25, "DEATHSCREAM3"),
    (26, "ATKMACHINEGUN"),
    (27, "HITENEMY"),
    (29, "DEATHSCREAM1"),
    (32, "SHOOT"),
    (41, "DOGBARK"),
    (51, "SCHUTZAD"),
    (52, "AHHHG"),
    (58, "NAZIFIRE"),
    (60, "SSFIRE"),
    (23, "ATKKNIFE"),
    (12, "GETKEY"),
    (30, "GETMACHINE"),
    (31, "GETAMMO"),
    (33, "HEALTH1"),
    (34, "HEALTH2"),
    (40, "LEVELDONE"),
    # Menu UI (also emitted alone as menu_pcsounds.asm for the boot MENU overlay)
    (4, "MOVEGUN2"),
    (5, "MOVEGUN1"),
    (39, "ESCPRESSED"),
]

# Boot menu only — small table; indices are local to menu.prg
MENU_CORE = [
    (4, "MOVEGUN2"),
    (5, "MOVEGUN1"),
    (32, "SHOOT"),
    (39, "ESCPRESSED"),
]
OUT_MENU_SOUNDS = ROOT / "src" / "menu_pcsounds.asm"

DECIMATE = 3
PC_BASE_TIMER = 1193181
PHI2_NTSC = 1022727
SID_CLOCK_DIV = 16777216
NUM_PC_SOUNDS = 87


def emit_bytes(arr: list[int], per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(arr), per_line):
        chunk = arr[i : i + per_line]
        lines.append("\t!byte " + ", ".join(str(b) for b in chunk))
    return "\n".join(lines)


def sid_fn(hz: float) -> int:
    if hz <= 0:
        return 0
    return max(0, min(65535, round((hz * SID_CLOCK_DIV) / PHI2_NTSC)))


def extract_pack(
    offs: list[int], aud: bytes, pack: list[tuple[int, str]], zone: str, header: str
) -> tuple[str, int]:
    blocks: list[str] = []
    priorities: list[int] = []
    labels: list[str] = []
    equates: list[str] = []
    total = 0

    for local_i, (wolf_i, name) in enumerate(pack):
        start = offs[wolf_i]
        end = offs[wolf_i + 1]
        chunk = aud[start:end]
        length, priority = struct.unpack_from("<IH", chunk, 0)
        data = list(chunk[6 : 6 + length])
        if len(data) != length:
            raise SystemExit(f"{name}: truncated PC chunk")
        samples = data[::DECIMATE]
        if len(samples) > 255:
            raise SystemExit(f"{name}: decimated length {len(samples)} > 255")
        body = [len(samples), *samples]
        total += len(body)
        label = f"pc_{name.lower()}"
        labels.append(label)
        priorities.append(priority & 0xFF)
        equates.append(f"SOUND_{name}\t= {local_i}")
        blocks.append(f"{label}\n{emit_bytes(body)}")

    table_lines = "\n".join(f"\t!word {lab}" for lab in labels)
    asm = (
        header
        + f"!zone {zone}\n"
        + "\n"
        + "\n".join(equates)
        + "\n\n"
        + "\n".join(blocks)
        + "\n\n"
        f"; unique sound payload {total} bytes\n"
        "sound_priorities\n"
        + emit_bytes(priorities)
        + "\n\n"
        "sound_table\n"
        + table_lines
        + "\n"
    )
    return asm, total


def main() -> None:
    hed = (SHAREWARE / "AUDIOHED.WL1").read_bytes()
    aud = (SHAREWARE / "AUDIOT.WL1").read_bytes()
    offs = [struct.unpack_from("<I", hed, i)[0] for i in range(0, len(hed), 4)]
    if len(offs) < NUM_PC_SOUNDS + 1:
        raise SystemExit(f"AUDIOHED too short: {len(offs)} offsets")

    core_header = (
        "; Autogenerated by tools/gensounds.py - CORE PC sounds from AUDIOT.WL1.\n"
        "; Each effect: first byte = sample count; following = Wolf inverse-freq bytes (0 = silence).\n"
        f"; Decimated {DECIMATE}x from 140 Hz source for ~50 Hz Timer A playback.\n"
        "\n"
    )
    sounds_asm, total = extract_pack(offs, aud, CORE, "pcsounds", core_header)
    OUT_SOUNDS.write_text(sounds_asm, encoding="utf-8", newline="\n")

    menu_header = (
        "; Autogenerated by tools/gensounds.py - menu UI PC sounds for MENU overlay.\n"
        "; MOVEGUN1/2 navigate+adjust, SHOOT select, ESCPRESSED back (Wolf WL_MENU.C).\n"
        f"; Decimated {DECIMATE}x from 140 Hz source for ~50 Hz Timer A playback.\n"
        "\n"
    )
    menu_asm, menu_total = extract_pack(
        offs, aud, MENU_CORE, "pcsounds", menu_header
    )
    OUT_MENU_SOUNDS.write_text(menu_asm, encoding="utf-8", newline="\n")

    hi: list[int] = []
    for b in range(256):
        if b == 0:
            fn = 0
        else:
            hz = PC_BASE_TIMER / (b * 60)
            fn = sid_fn(hz)
        hi.append((fn >> 8) & 0xFF)

    freq_asm = (
        "; Autogenerated by tools/gensounds.py - Wolf PC byte -> SID Fn hi (NTSC phi2).\n"
        "; Index = AUDIOT sample byte (0 = silence). hz = 1193181/(byte*60).\n"
        "; Playback writes Fn lo = $80 (see playsound.asm); only hi is tabled.\n"
        "\n"
        "!zone pcsfreq\n"
        "\n"
        "pcsfreq_hi\n"
        + emit_bytes(hi)
        + "\n"
    )
    OUT_FREQ.write_text(freq_asm, encoding="utf-8", newline="\n")
    print(
        f"wrote {OUT_SOUNDS.relative_to(ROOT)} ({len(CORE)} effects, {total} sample bytes) "
        f"+ {OUT_MENU_SOUNDS.relative_to(ROOT)} ({len(MENU_CORE)} effects, {menu_total} sample bytes) "
        f"+ {OUT_FREQ.relative_to(ROOT)} (256 hi entries)"
    )


if __name__ == "__main__":
    main()
