#!/usr/bin/env python3
"""Build painter_tables.asm from painters.lbl + painters.asm (byte_off)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LBL = ROOT / "painters.lbl"
PAINTERS_ASM = ROOT / "src" / "painters.asm"
OUT = ROOT / "src" / "painter_tables.asm"
MAX_HALF_H = 75
NEAR_LO = 51


def load_labels(path: Path) -> dict[str, int]:
	addrs: dict[str, int] = {}
	for line in path.read_text().splitlines():
		m = re.match(r"al C:([0-9a-fA-F]+) \.(\S+)", line)
		if m:
			addrs[m.group(2)] = int(m.group(1), 16)
	return addrs


def load_byte_offs(path: Path) -> dict[str, int]:
	"""Map smc_* label → TEXTURES byte_off from 'lda TEXTURES + N,x'."""
	offs: dict[str, int] = {}
	cur: str | None = None
	for line in path.read_text().splitlines():
		m = re.match(r"(smc_h\d{2}_\d+)\s*$", line.strip())
		if m:
			cur = m.group(1)
			continue
		if cur:
			m = re.search(r"lda\s+TEXTURES\s*\+\s*(\d+)\s*,\s*x", line)
			if m:
				offs[cur] = int(m.group(1))
				cur = None
	return offs


def main() -> None:
	addrs = load_labels(LBL)
	offs = load_byte_offs(PAINTERS_ASM)
	lines = [
		"; AUTO-GENERATED by tools/make_painter_tables.py — do not edit",
		"!zone painter_tables",
		"",
		"painter_lo",
		"\t!byte 0",
	]
	los = [f"${addrs[f'painter_h{h:02d}'] & 255:02x}" for h in range(1, MAX_HALF_H + 1)]
	his = [f"${addrs[f'painter_h{h:02d}'] >> 8:02x}" for h in range(1, MAX_HALF_H + 1)]
	for i in range(0, MAX_HALF_H, 16):
		lines.append("\t!byte " + ", ".join(los[i : i + 16]))
	lines.append("painter_hi")
	lines.append("\t!byte 0")
	for i in range(0, MAX_HALF_H, 16):
		lines.append("\t!byte " + ", ".join(his[i : i + 16]))
	lines.append("")

	smc_re = re.compile(r"smc_h(\d{2})_(\d+)$")
	by_h: list[list[tuple[str, int]]] = [[] for _ in range(MAX_HALF_H + 1)]
	for name, addr in addrs.items():
		m = smc_re.match(name)
		if m:
			h = int(m.group(1))
			if h <= MAX_HALF_H:
				by_h[h].append((name, addr))

	missing = 0
	for h in range(1, MAX_HALF_H + 1):
		by_h[h].sort(key=lambda t: t[1])
		lines.append(f"ph_patch_h{h:02d}")
		if h >= NEAR_LO:
			# Looped near painters: tex_ptr only, no LDA sites to patch
			lines.append("\t!byte 0")
			lines.append("")
			continue
		lines.append(f"\t!byte {len(by_h[h])}")
		parts: list[str] = []
		for name, addr in by_h[h]:
			op_lo = addr + 1  # LDA abs,x operand lo
			byte_off = offs.get(name)
			if byte_off is None:
				missing += 1
				byte_off = 0
			parts.append(f"${op_lo & 255:02x}")
			parts.append(f"${op_lo >> 8:02x}")
			parts.append(f"${byte_off:02x}")
			if len(parts) >= 15:
				lines.append("\t!byte " + ", ".join(parts))
				parts = []
		if parts:
			lines.append("\t!byte " + ", ".join(parts))
		lines.append("")

	lines.append("ph_patch_lo")
	lines.append("\t!byte 0")
	plo = [f"<ph_patch_h{h:02d}" for h in range(1, MAX_HALF_H + 1)]
	phi = [f">ph_patch_h{h:02d}" for h in range(1, MAX_HALF_H + 1)]
	for i in range(0, MAX_HALF_H, 16):
		lines.append("\t!byte " + ", ".join(plo[i : i + 16]))
	lines.append("ph_patch_hi")
	lines.append("\t!byte 0")
	for i in range(0, MAX_HALF_H, 16):
		lines.append("\t!byte " + ", ".join(phi[i : i + 16]))
	lines.append("")

	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
	total = sum(len(by_h[h]) for h in range(1, MAX_HALF_H + 1))
	print(f"Wrote {OUT} (SMC sites: {total}, missing offs: {missing})")


if __name__ == "__main__":
	main()
