#!/usr/bin/env python3
"""
Pack world-item C64 edit sheet into textures/items.bin + src/items/item_gfx.asm.

Reads (hand-edited) sheet — not the regenerations:

  textures/items/c64/items_c64_sheet_edit.png

Blob + LUTs link at ITEM_SPRITES ($5880), budget to BITMAP ($6000) = 1920 bytes.

Layout per frame (column-major 4bpp, nibble 0 = transparent) — same as enemies:
  For x in 0..w-1:
    for y in 0..h-1 step 2:
      byte = (pix[y] << 4) | (pix[y+1] if y+1 < h else 0)
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pack_enemies import frame_indices, opaque_bbox, pack_columns  # noqa: E402
from process_items_c64 import OUT_COLS, OUT_ROWS  # noqa: E402

# Sheet order from process_items_c64 detect_boxes (row-major, 5×4).
ITEM_FRAMES: list[str] = [
    "table_chairs",
    "chandelier",
    "hanged_man",
    "dog_food",
    "tree",
    "urn",
    "ceiling_light",
    "skeleton_cage",
    "key_gold",
    "key_silver",
    "food",
    "firstaid",
    "ammo_clip",
    "machinegun",
    "chaingun",
    "gibs",
    "well",
    "flag",
    "puddle",
    "bed",
]

CEILING_ITEMS = frozenset(
    {"chandelier", "ceiling_light", "hanged_man", "skeleton_cage"}
)

ITEM_BUDGET = 0x6000 - 0x5880  # BITMAP - ITEM_SPRITES


def if_symbol(name: str) -> str:
    return "IF_" + name.upper()


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    sheet_path = root / "textures" / "items" / "c64" / "items_c64_sheet_edit.png"
    out_bin = root / "textures" / "items.bin"
    out_asm = root / "src" / "items" / "item_gfx.asm"

    if not sheet_path.is_file():
        raise FileNotFoundError(sheet_path)
    if len(ITEM_FRAMES) > OUT_COLS * OUT_ROWS:
        raise ValueError(
            f"{len(ITEM_FRAMES)} frames > {OUT_COLS}x{OUT_ROWS} sheet"
        )

    sheet = Image.open(sheet_path).convert("RGBA")
    sw, sh = sheet.size
    if sw % OUT_COLS or sh % OUT_ROWS:
        raise ValueError(
            f"sheet {sw}x{sh} not divisible by {OUT_COLS}x{OUT_ROWS} grid"
        )
    cell_w = sw // OUT_COLS
    cell_h = sh // OUT_ROWS
    print(f"{sheet_path.name}  {sw}x{sh}  cells {cell_w}x{cell_h}")

    blob = bytearray()
    widths: list[int] = []
    heights: list[int] = []
    offsets: list[int] = []
    ceilings: list[int] = []

    for i, name in enumerate(ITEM_FRAMES):
        col = i % OUT_COLS
        row = i // OUT_COLS
        cell = sheet.crop(
            (col * cell_w, row * cell_h, (col + 1) * cell_w, (row + 1) * cell_h)
        )
        bbox = opaque_bbox(cell)
        if bbox is None:
            raise ValueError(f"empty cell for {name} at col={col} row={row}")
        frame = cell.crop(bbox)
        w, h, idx = frame_indices(frame)
        off = len(blob)
        chunk = pack_columns(w, h, idx)
        blob.extend(chunk)
        widths.append(w)
        heights.append(h)
        offsets.append(off)
        ceilings.append(1 if name in CEILING_ITEMS else 0)
        print(
            f"  {name:16} {w:2}x{h:<2}  off={off:4}  bytes={len(chunk)}"
            f"{'  ceil' if ceilings[-1] else ''}"
        )

    n = len(ITEM_FRAMES)
    # LUTs reside with the blob at ITEM_SPRITES (5 tables × n bytes).
    lut_bytes = 5 * n
    total = lut_bytes + len(blob)
    print(f"\nblob={len(blob)}  luts={lut_bytes}  total={total}  budget={ITEM_BUDGET}")
    if total > ITEM_BUDGET:
        raise SystemExit(
            f"item gfx does not fit: {total} bytes > {ITEM_BUDGET} "
            f"($5880-$5FFF)"
        )

    out_bin.write_bytes(blob)
    print(f"Wrote {out_bin} ({len(blob)} bytes, {n} frames)")

    out_asm.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; Auto-generated by tools/pack_items.py — do not edit",
        "!zone item_gfx",
        f"ITEM_FRAME_COUNT = {n}",
        "",
        "item_frm_w",
        "\t!byte " + ", ".join(str(w) for w in widths),
        "item_frm_h",
        "\t!byte " + ", ".join(str(h) for h in heights),
        "item_frm_off_lo",
        "\t!byte " + ", ".join(str(o & 0xFF) for o in offsets),
        "item_frm_off_hi",
        "\t!byte " + ", ".join(str((o >> 8) & 0xFF) for o in offsets),
        "item_frm_ceil",
        "\t!byte " + ", ".join(str(c) for c in ceilings),
        "",
    ]
    for i, name in enumerate(ITEM_FRAMES):
        lines.append(f"{if_symbol(name)} = {i}")
    lines.append("")
    lines.append("; item_gfx_data label lives in wolf64.asm (ITM load → ITEM_SPRITES)")
    lines.append("")

    out_asm.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_asm}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
