#!/usr/bin/env python3
"""
Pack textures/guards/c64_16/guards_c64_sheet_edit.png into textures/enemies.bin
+ src/enemy_gfx.asm LUTs.

Edit that file by hand (muzzle flash, etc.). process_guard_c64.py still writes
guards_c64_16_sheet.png from the VSWAP source sheet — that path is NOT used by the packer.

Sheet layout: 5 columns × 4 rows, row-major SELECTED order, equal cells.
Each cell is opaque-bbox cropped before packing.

Layout per frame (column-major 4bpp, nibble 0 = transparent):
  For x in 0..w-1:
    for y in 0..h-1 step 2:
      byte = (pix[y] << 4) | (pix[y+1] if y+1 < h else 0)

Frame order (20): stand 1..5, walkA 1..5, walkB 1..5, die1, pain2, dead, shoot2, shoot3
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_walls import C64_PALETTE  # noqa: E402
from process_guard_c64 import SELECTED  # noqa: E402

RGB_TO_IDX = {rgb: i for i, rgb in enumerate(C64_PALETTE)}
SHEET_COLS = 5
SHEET_ROWS = 4
SHEET_NAME = "guards_c64_sheet_edit.png"
FRAME_NAMES = [name for name, _, _ in SELECTED]


def opaque_bbox(img: Image.Image) -> tuple[int, int, int, int] | None:
    px = img.load()
    w, h = img.size
    xs: list[int] = []
    ys: list[int] = []
    for y in range(h):
        for x in range(w):
            if px[x, y][3] > 128:
                xs.append(x)
                ys.append(y)
    if not xs:
        return None
    return min(xs), min(ys), max(xs) + 1, max(ys) + 1


def frame_indices(img: Image.Image) -> tuple[int, int, list[int]]:
    """RGBA → (w, h, row-major indices; transparent → 0). Exact Pepto RGB only."""
    img = img.convert("RGBA")
    w, h = img.size
    px = img.load()
    out: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 128:
                out.append(0)
            else:
                out.append(RGB_TO_IDX.get((r, g, b), 0) & 0x0F)
    return w, h, out


def pack_columns(w: int, h: int, row_major: list[int]) -> bytes:
    """Column-major 4bpp (two vertical texels per byte)."""
    blob = bytearray()
    for x in range(w):
        for y in range(0, h, 2):
            hi = row_major[y * w + x] & 0x0F
            lo = row_major[(y + 1) * w + x] & 0x0F if y + 1 < h else 0
            blob.append((hi << 4) | lo)
    return bytes(blob)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    sheet_path = root / "textures" / "guards" / "c64_16" / SHEET_NAME
    out_bin = root / "textures" / "enemies.bin"
    out_asm = root / "src" / "enemy_gfx.asm"

    if not sheet_path.is_file():
        raise FileNotFoundError(sheet_path)

    assert len(FRAME_NAMES) == SHEET_COLS * SHEET_ROWS, len(FRAME_NAMES)

    sheet = Image.open(sheet_path).convert("RGBA")
    sw, sh = sheet.size
    if sw % SHEET_COLS or sh % SHEET_ROWS:
        raise ValueError(
            f"sheet {sw}x{sh} not divisible by {SHEET_COLS}x{SHEET_ROWS} grid"
        )
    cell_w = sw // SHEET_COLS
    cell_h = sh // SHEET_ROWS
    print(f"edit sheet {sheet_path.name}  {sw}x{sh}  cells {cell_w}x{cell_h}")

    widths: list[int] = []
    heights: list[int] = []
    offsets: list[int] = []
    blob = bytearray()

    for i, name in enumerate(FRAME_NAMES):
        col = i % SHEET_COLS
        row = i // SHEET_COLS
        cell = sheet.crop(
            (col * cell_w, row * cell_h, (col + 1) * cell_w, (row + 1) * cell_h)
        )
        bbox = opaque_bbox(cell)
        if bbox is None:
            raise ValueError(f"empty cell for {name} at col={col} row={row}")
        frame = cell.crop(bbox)
        w, h, idx = frame_indices(frame)
        off = len(blob)
        chunk = pack_columns(w, h, idx)
        blob.extend(chunk)
        widths.append(w)
        heights.append(h)
        offsets.append(off)
        print(f"{name:16} {w:2}x{h:<2}  off={off:4}  bytes={len(chunk)}")

    out_bin.write_bytes(blob)
    print(f"Wrote {out_bin} ({len(blob)} bytes)")

    lines = [
        "; Auto-generated by tools/pack_enemies.py — do not edit",
        "!zone enemy_gfx",
        f"ENEMY_FRAME_COUNT = {len(FRAME_NAMES)}",
        "",
        "enemy_frm_w",
        "\t!byte " + ", ".join(str(w) for w in widths),
        "enemy_frm_h",
        "\t!byte " + ", ".join(str(h) for h in heights),
        "enemy_frm_off_lo",
        "\t!byte " + ", ".join(str(o & 0xFF) for o in offsets),
        "enemy_frm_off_hi",
        "\t!byte " + ", ".join(str((o >> 8) & 0xFF) for o in offsets),
        "",
        "; Frame sets: stand=0..4  walkA=5..9  walkB=10..14; combat 15..19",
        "EF_STAND = 0",
        "EF_WALKA = 5",
        "EF_WALKB = 10",
        "EF_DIE = 15",
        "EF_PAIN = 16",
        "EF_DEAD = 17",
        "EF_SHOOT2 = 18",
        "EF_SHOOT3 = 19",
        "",
        "; enemy_gfx_data label lives in wolf64.asm (after SoA)",
        "",
    ]
    out_asm.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_asm}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
