; BSS overlays disposable boot at LOADER_BASE..REBOOT_STUB-1 (not emitted).
; col_wallz_h / col_enemy after end_sfx; reboot stub @ REBOOT_STUB; difficulty @ $08FF.
; Generated by tools/gen_bss.py — chained '=' for ACME multi-pass.
!zone bss

col_texid	= LOADER_BASE
col_half_h	= col_texid + 40
col_texx	= col_half_h + 40
col_wallz_l	= col_texx + 40
load_namelen	= col_wallz_l + 40
load_name_l	= load_namelen + 1
load_name_h	= load_name_l + 1
load_do_pad	= load_name_h + 1
load_jiffy0	= load_do_pad + 1
episode	= load_jiffy0 + 1
level_num	= episode + 1
secret_from	= level_num + 1
load_in_play	= secret_from + 1
end_bss	= load_in_play + 1
!if end_bss > REBOOT_STUB {
	!error "BSS overlaps REBOOT_STUB; end_bss=$", end_bss
}
