; BSS overlays disposable boot at LOADER_BASE..LOCODE_BASE-1 (not emitted).
; Other BSS (!fill) lives after locode / after painters as before.
; Generated by tools/gen_bss.py — chained '=' for ACME multi-pass.
!zone bss

col_texid	= LOADER_BASE
col_half_h	= col_texid + 40
col_texx	= col_half_h + 40
col_wallz_l	= col_texx + 40
col_wallz_h	= col_wallz_l + 40
col_enemy	= col_wallz_h + 40
sound_priority	= col_enemy + 40
sound_count	= sound_priority + 1
sound_max	= sound_count + 1
ps_save_x	= sound_max + 1
ps_save_y	= ps_save_x + 1
load_namelen	= ps_save_y + 1
load_name_l	= load_namelen + 1
load_name_h	= load_name_l + 1
load_do_pad	= load_name_h + 1
load_jiffy0	= load_do_pad + 1
episode	= load_jiffy0 + 1
level_num	= episode + 1
end_bss	= level_num + 1
!if end_bss > LOCODE_BASE {
	!error "BSS overlaps LOCODE_BASE; end_bss=$", end_bss
}
