; Auto-generated by tools/gen_enemy_painters.py — do not edit
!zone enemy_painters
ENEMY_MAX_H = 48
ENEMY_SRC_H = 16

; 8.8 step: src_row += step each chunky screen row (src height 16)
enemy_vstep_lo
	!byte 0, 0, 0, 85, 0, 51, 170, 73, 0, 199, 153, 116, 85, 59, 36, 17, 0, 240, 227, 215, 204, 195, 186, 178, 170, 163, 157, 151, 146, 141, 136, 132, 128, 124, 120, 117, 113, 110, 107, 105, 102, 99, 97, 95, 93, 91, 89, 87, 85
enemy_vstep_hi
	!byte 0, 16, 8, 5, 4, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

