; Auto-generated by tools/pack_enemies.py — do not edit
!zone enemy_gfx
ENEMY_FRAME_COUNT = 66

EG_GUARD = 0
EG_DOG = 20
EG_SS = 35
EG_HANS = 55

enemy_frm_w
	!byte 7, 6, 5, 6, 7, 6, 8, 10, 9, 7, 8, 7, 6, 6, 7, 9, 10, 14, 7, 7, 11, 13, 19, 13, 10, 10, 16, 20, 16, 10, 13, 21, 18, 6, 13, 9, 7, 5, 7, 9, 8, 7, 11, 9, 9, 8, 7, 9, 8, 9, 9, 9, 15, 7, 7, 14, 15, 13, 15, 15, 15, 15, 14, 14, 14, 14
enemy_frm_h
	!byte 16, 16, 16, 16, 16, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 16, 5, 16, 16, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 4, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 13, 15, 5, 16, 16, 16, 16, 16, 16, 16, 16, 16, 5, 15, 14, 10
enemy_frm_off_lo
	!byte 0, 56, 104, 144, 192, 248, 40, 104, 184, 0, 56, 120, 176, 224, 16, 72, 144, 224, 10, 66, 122, 188, 10, 124, 202, 6, 66, 162, 26, 122, 182, 4, 130, 166, 214, 62, 134, 190, 230, 30, 102, 166, 222, 54, 126, 198, 6, 62, 134, 198, 14, 77, 149, 194, 250, 50, 162, 26, 130, 250, 114, 234, 98, 140, 252, 94
enemy_frm_off_hi
	!byte 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 15, 15, 15, 16, 16, 17, 17, 17, 18

; Guard / SS relative (add EG_GUARD or EG_SS)
EF_STAND = 0
EF_WALKA = 5
EF_WALKB = 10
EF_DIE = 15
EF_PAIN = 16
EF_DEAD = 17
EF_SHOOT2 = 18
EF_SHOOT3 = 19

; Dog absolute indices
EF_DOG_WALKA = 20
EF_DOG_WALKB = 25
EF_DOG_DIE = 30
EF_DOG_DIE3 = 31
EF_DOG_DEAD = 32
EF_DOG_JUMP1 = 33
EF_DOG_JUMP2 = 34

; Hans absolute indices
EF_HANS_W1 = 55
EF_HANS_W2 = 56
EF_HANS_W3 = 57
EF_HANS_W4 = 58
EF_HANS_SHOOT1 = 59
EF_HANS_SHOOT2 = 60
EF_HANS_SHOOT3 = 61
EF_HANS_DEAD = 62
EF_HANS_DIE1 = 63
EF_HANS_DIE2 = 64
EF_HANS_DIE3 = 65

; enemy_gfx_data label lives in wolf64.asm (SFX load image → SFX_BASE)

