; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root

control_text
	!scr "^WASD....^ Forward/backward/strafe",0
	!scr "^IJKL....^ Forward/backward/turn",0
	!scr "^Space...^ Fire",0
	!scr "^1234....^ Change weapon",0
	!scr " ",0
	!scr "If you have a mouse in port 1 and",0
	!scr "you have enabled it in the Options,",0
	!scr "you can turn and shoot with it.",0
	!scr " ",0
	!scr "Walk into doors to open them.",0
	!scr "Walk into secret walls to push them.",0
	!scr "Walk over items to pick them up.",0
	!byte 0

credits_text
	!scr "Wolfenstein 3d is a trademark of",0
	!scr "ID Software LLC/Zenimax Media Inc.",0
	!scr "Unofficial Commodore 64 fan port",0
	!scr "created by Steve McCrea in 2026.",0
	!scr "Not affiliated with or endorsed",0
	!scr "by ID Software or Zenimax.",0
	!scr "For non-commercial/fan use only.",0
	!scr " ",0
	!scr "Wolfenstein 3d was created by",0
	!scr "John Carmack, John Romero,",0
	!scr "Adrian Carmack, Tom Hall,",0
	!scr "Kevin Cloud, Bobby Prince,",0
	!scr "Jay Wilbur, and Jason Blochowiak.",0
	!scr " ",0
	!scr "v1.4",0
	!byte 0

order_text
	!scr "Episodes 2 through 6 are not",0
	!scr "available in this shareware",0
	!scr "version.",0
	!scr " ",0
	!scr "To order the full trilogy or",0
	!scr "all six episodes, please call",0
	!scr "Apogee at",0
	!scr " ",0
	!scr "1-800-GAME-123",0
	!byte 0

readthis1_text
	!scr "You stand over the guard's body,",0
	!scr "grabbing frantically for his gun.",0
	!scr "You're not sure if the other guards",0
	!scr "heard his muffled scream. Deep in",0
	!scr "the belly of a Nazi dungeon, your",0
	!scr "only ticket out is your knife,",0
	!scr "a stolen pistol, and raw grit.",0
	!byte 0

readthis2a_text
	!scr "Weeks ago, you were dropped",0
	!scr "behind enemy lines on a suicide",0
	!scr "mission: infiltrate the Nazi",0
	!scr "fortress and steal the secret",0
	!scr "plans for Operation Eisenfaust.",0
	!scr " ",0
	!scr "Ambushed and captured, you",0
	!scr "were dragged into their deepest",0
	!scr "dungeon to await a firing squad.",0
	!byte 0

readthis2b_text
	!scr "Only you know where the plans are",0
	!scr "kept, and if you don't escape, the",0
	!scr "Allied war effort is doomed!",0
	!scr " ",0
	!scr "You must confront the horrors of",0
	!scr "the prison fortress known as...",0
	!scr "Wolfenstein!",0
	!byte 0

readthis3_text
	!scr "Captain William J. \"B.J.\" Blazkowicz,",0
	!scr "you've got eight slugs and eight",0
	!scr "floors of hell to wade through.",0
	!scr " ",0
	!scr "Good luck!",0
	!byte 0

ending1_text
	!scr "CONGRATULATIONS!",0
	!scr " ",0
	!scr "You run out of the castle and hook",0
	!scr "up with the Underground. They inform",0
	!scr "you that the rumors were true:",0
	!scr "some hideous human experiments were",0
	!scr "seen around Castle Hollehammer.",0
	!scr " ",0
	!scr "So Operation Eisenfaust is real!",0
	!byte 0

ending2_text
	!scr "You must journey there and terminate",0
	!scr "the maniacal Dr. Schabbs before his",0
	!scr "undead army marches against",0
	!scr "humanity!",0
	!scr " ",0
	!scr "Continue the game in",0
	!scr "Episode 2: Operation Eisenfaust!",0
	!byte 0
