; Autogenerated by tools/gensounds.py - menu UI PC sounds for MENU overlay.
; MOVEGUN1/2 navigate+adjust, SHOOT select, ESCPRESSED back (Wolf WL_MENU.C).
; Decimated 3x from 140 Hz source for ~50 Hz Timer A playback.

!zone pcsounds

SOUND_MOVEGUN2	= 0
SOUND_MOVEGUN1	= 1
SOUND_SHOOT	= 2
SOUND_ESCPRESSED	= 3

pc_movegun2
	!byte 2, 142, 148
pc_movegun1
	!byte 3, 114, 60, 114
pc_shoot
	!byte 9, 16, 110, 40, 40, 33, 103, 41, 115, 137
pc_escpressed
	!byte 8, 153, 130, 113, 95, 78, 55, 45, 32

; unique sound payload 26 bytes
sound_priorities
	!byte 1, 1, 20, 10

sound_table
	!word pc_movegun2
	!word pc_movegun1
	!word pc_shoot
	!word pc_escpressed
