; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root

control_text
	!scr "^W.......^ Forward",0
	!scr "^S.......^ Backward",0
	!scr "^A.......^ Strafe Left",0
	!scr "^D.......^ Strafe Right",0
	!scr "^J.......^ Turn Left",0
	!scr "^L.......^ Turn Right",0
	!scr "^Space...^ Fire",0
	!scr "^1-4.....^ Change weapon",0
	!scr " ",0
	!scr "Walk into doors to open them.",0
	!scr "Walk into secret walls to push them.",0
	!scr "Walk over items to pick them up.",0
	!byte 0

credits_text
	!scr "Wolfenstein 3d is a trademark of",0
	!scr "ID Software LLC/Zenimax Media Inc.",0
	!scr "Unofficial C64 fan port created",0
	!scr "by Steve McCrea in 2026.",0
	!scr "Not affiliated with or endorsed",0
	!scr "by ID Software or Zenimax.",0
	!scr "For non-commercial/fan use only.",0
	!scr " ",0
	!scr "Wolfenstein 3d was created by",0
	!scr "John Carmack, John Romero,",0
	!scr "Adrian Carmack, Tom Hall,",0
	!scr "Kevin Cloud, Bobby Prince,",0
	!scr "Jay Wilbur, and Jason Blochowiak.",0
	!byte 0

order_text
	!scr "Episodes 2 through 6 are not",0
	!scr "available in this shareware",0
	!scr "version.",0
	!scr " ",0
	!scr "To order the full trilogy or",0
	!scr "all six episodes, please call",0
	!scr "Apogee at",0
	!scr " ",0
	!scr "1-800-GAME-123",0
	!byte 0

readthis1_text
	!scr "You stand over the guard's body,",0
	!scr "grabbing frantically for his gun.",0
	!scr "You're not sure if the other guards",0
	!scr "heard his muffled scream. Deep in",0
	!scr "the belly of a Nazi dungeon, you've",0
	!scr "only a knife, a gun, and your wits",0
	!scr "to aid your escape.",0
	!byte 0

readthis2a_text
	!scr "Just a few weeks ago you were on a",0
	!scr "reconnaissance mission of extreme",0
	!scr "importance. You were to infiltrate",0
	!scr "the Nazi fortress and find the plans",0
	!scr "for Operation Eisenfaust.",0
	!scr " ",0
	!scr "Captured in your attempt, you were",0
	!scr "taken to their prison, and awaited",0
	!scr "your execution.",0
	!byte 0

readthis2b_text
	!scr "Only you know where the plans are",0
	!scr "kept, and the Allies will face a great",0
	!scr "defeat if you don't escape!",0
	!scr " ",0
	!scr "You must face the horrors of the",0
	!scr "prison keep known as Wolfenstein.",0
	!byte 0

readthis3_text
	!scr "Captain William J. \"B.J.\" Blazkowicz,",0
	!scr "you've got a gun and eight floors of",0
	!scr "hell to get through.",0
	!scr " ",0
	!scr "Good luck!",0
	!byte 0

ending1_text
	!scr "CONGRATULATIONS!",0
	!scr " ",0
	!scr "You run out of the castle and hook up",0
	!scr "with the Underground. They inform you",0
	!scr "that the rumors were true: some hideous",0
	!scr "human experiments were seen around",0
	!scr "Castle Hollehammer.",0
	!scr " ",0
	!scr "So Operation Eisenfaust is real!",0
	!byte 0

ending2_text
	!scr "You must journey there and terminate",0
	!scr "the maniacal Dr. Schabbs before his",0
	!scr "undead army marches against humanity!",0
	!scr " ",0
	!scr "Continue the game in",0
	!scr "Episode 2: Operation Eisenfaust!",0
	!byte 0
