; Auto-generated by tools/gen_menu_text.py - edit *.txt in repo root

control_text
	!scr "^W^....... Forward",0
	!scr "^S^....... Backward",0
	!scr "^A^....... Strafe Left",0
	!scr "^D^....... Strafe Right",0
	!scr "^J^....... Turn Left",0
	!scr "^L^....... Turn Right",0
	!scr "^Space^... Fire",0
	!scr "^1^-^4^..... Change weapon",0
	!scr " ",0
	!scr "Walk into doors to open them.",0
	!scr "Walk over items to pick them up.",0
	!byte 0

credits_text
	!scr "Wolfenstein 3d is a trademark of",0
	!scr "ID Software LLC/Zenimax Media Inc.",0
	!scr "Unofficial C64 fan port created",0
	!scr "by Steve McCrea in 2026.",0
	!scr "Not affiliated with or endorsed",0
	!scr "by ID Software or Zenimax.",0
	!scr "For non-commercial/fan use only.",0
	!scr " ",0
	!scr "Wolfenstein 3d was created by",0
	!scr "John Carmack, John Romero,",0
	!scr "Adrian Carmack, Tom Hall,",0
	!scr "Kevin Cloud, Bobby Prince,",0
	!scr "Jay Wilbur, and Jason",0
	!scr "Blochowiak.",0
	!byte 0

order_text
	!scr "Episodes 2 through 6 are not",0
	!scr "available in this shareware",0
	!scr "version.",0
	!scr " ",0
	!scr "To order the full trilogy or",0
	!scr "all six episodes, please call",0
	!scr "Apogee at",0
	!scr " ",0
	!scr "1-800-GAME-123",0
	!byte 0

readthis1_text
	!scr "You stand over the guard's body,",0
	!scr "grabbing frantically for his",0
	!scr "gun. You're not sure if the",0
	!scr "other guards heard his muffled",0
	!scr "scream. Deep in the belly of a",0
	!scr "Nazi dungeon, you've only a",0
	!scr "knife, a gun, and your wits to",0
	!scr "aid your escape.",0
	!byte 0

readthis2_text
	!scr "Just a few weeks ago you were on",0
	!scr "a reconnaissance mission of",0
	!scr "extreme importance. You were to",0
	!scr "infiltrate the Nazi fortress and",0
	!scr "find the plans for Operation",0
	!scr "Eisenfaust. Captured in your",0
	!scr "attempt, you were taken to their",0
	!scr "prison, and awaited your",0
	!scr "execution. Only you know where",0
	!scr "the plans are kept, and the",0
	!scr "Allies will face a great defeat",0
	!scr "if you don't escape! You must",0
	!scr "face the horrors of the prison",0
	!scr "keep known as Wolfenstein.",0
	!byte 0

readthis3_text
	!scr "Captain William J. \"B.J.\"",0
	!scr "Blazkowicz, you've got a gun and",0
	!scr "eight floors of hell to get",0
	!scr "through.",0
	!scr " ",0
	!scr "Good luck!",0
	!byte 0
