; Autogenerated by tools/gensounds.py - CORE PC sounds from AUDIOT.WL1.
; Each effect: first byte = sample count; following = Wolf inverse-freq bytes (0 = silence).
; Decimated 3x from 140 Hz source for ~50 Hz Timer A playback.

!zone pcsounds

SOUND_HITWALL	= 0
SOUND_PLAYERDEATH	= 1
SOUND_DOGDEATH	= 2
SOUND_ATKGATLING	= 3
SOUND_TAKEDAMAGE	= 4
SOUND_OPENDOOR	= 5
SOUND_CLOSEDOOR	= 6
SOUND_HALT	= 7
SOUND_DEATHSCREAM2	= 8
SOUND_ATKPISTOL	= 9
SOUND_DEATHSCREAM3	= 10
SOUND_ATKMACHINEGUN	= 11
SOUND_HITENEMY	= 12
SOUND_DEATHSCREAM1	= 13
SOUND_SHOOT	= 14
SOUND_DOGBARK	= 15
SOUND_SCHUTZAD	= 16
SOUND_AHHHG	= 17
SOUND_NAZIFIRE	= 18
SOUND_SSFIRE	= 19
SOUND_ATKKNIFE	= 20

pc_hitwall
	!byte 3, 131, 142, 134
pc_playerdeath
	!byte 16, 21, 30, 39, 45, 52, 15, 77, 98, 17, 0, 0, 0, 0, 0, 0
	!byte 79
pc_dogdeath
	!byte 15, 19, 16, 15, 27, 40, 43, 57, 69, 83, 0, 111, 157, 0, 152, 159
pc_atkgatling
	!byte 5, 61, 57, 59, 93, 66
pc_takedamage
	!byte 19, 62, 59, 55, 52, 49, 63, 75, 80, 69, 78, 65, 77, 68, 62, 56
	!byte 74, 67, 61, 55
pc_opendoor
	!byte 12, 119, 118, 118, 116, 114, 111, 107, 101, 95, 89, 83, 77
pc_closedoor
	!byte 12, 79, 83, 85, 87, 90, 93, 96, 101, 104, 106, 109, 112
pc_halt
	!byte 25, 42, 38, 35, 31, 31, 31, 32, 46, 60, 77, 85, 105, 132, 140, 145
	!byte 148, 151, 153, 157, 0, 0, 0, 138, 138, 138
pc_deathscream2
	!byte 20, 81, 78, 80, 87, 95, 107, 119, 120, 119, 113, 109, 120, 123, 139, 140
	!byte 136, 148, 152, 152, 157
pc_atkpistol
	!byte 22, 24, 33, 33, 157, 36, 158, 69, 159, 135, 147, 154, 159, 0, 0, 147
	!byte 149, 0, 0, 154, 0, 0, 151
pc_deathscream3
	!byte 32, 35, 31, 28, 26, 27, 38, 67, 75, 80, 82, 82, 82, 82, 80, 79
	!byte 77, 77, 76, 77, 79, 84, 92, 95, 96, 95, 93, 93, 95, 101, 112, 116
	!byte 121
pc_atkmachinegun
	!byte 4, 104, 107, 101, 0
pc_hitenemy
	!byte 10, 130, 25, 33, 78, 26, 18, 0, 0, 0, 0
pc_deathscream1
	!byte 20, 60, 55, 51, 26, 37, 31, 15, 16, 23, 29, 74, 28, 31, 27, 34
	!byte 42, 38, 34, 36, 41
pc_shoot
	!byte 9, 16, 110, 40, 40, 33, 0, 0, 0, 0
pc_dogbark
	!byte 17, 64, 56, 47, 41, 142, 144, 37, 48, 144, 57, 67, 82, 93, 104, 123
	!byte 0, 151
pc_schutzad
	!byte 24, 43, 35, 30, 26, 18, 18, 18, 21, 28, 101, 37, 60, 0, 0, 63
	!byte 72, 92, 114, 105, 87, 106, 117, 124, 128
pc_ahhhg
	!byte 33, 0, 72, 73, 73, 73, 73, 73, 72, 72, 72, 71, 71, 70, 70, 70
	!byte 69, 68, 67, 66, 65, 64, 62, 60, 58, 56, 55, 51, 48, 45, 42, 39
	!byte 36, 34
pc_nazifire
	!byte 20, 24, 24, 21, 21, 20, 0, 0, 104, 0, 0, 102, 0, 126, 115, 133
	!byte 0, 0, 137, 136, 139
pc_ssfire
	!byte 22, 0, 0, 51, 41, 32, 0, 52, 42, 0, 59, 54, 45, 52, 31, 0
	!byte 0, 0, 0, 49, 49, 38, 72
pc_atkknife
	!byte 14, 84, 17, 62, 71, 75, 90, 104, 121, 106, 149, 130, 138, 156, 154

; unique sound payload 375 bytes
sound_priorities
	!byte 1, 99, 50, 50, 90, 20, 20, 50, 50, 50, 50, 50, 50, 50, 20, 50
	!byte 50, 50, 50, 50, 49

sound_table
	!word pc_hitwall
	!word pc_playerdeath
	!word pc_dogdeath
	!word pc_atkgatling
	!word pc_takedamage
	!word pc_opendoor
	!word pc_closedoor
	!word pc_halt
	!word pc_deathscream2
	!word pc_atkpistol
	!word pc_deathscream3
	!word pc_atkmachinegun
	!word pc_hitenemy
	!word pc_deathscream1
	!word pc_shoot
	!word pc_dogbark
	!word pc_schutzad
	!word pc_ahhhg
	!word pc_nazifire
	!word pc_ssfire
	!word pc_atkknife
